name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
content: config-prettier.write/sets-up::rakeo@uild_script.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3.3.0
    - name: Setup Node.js
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # tag: v3.6.0
      with:
        node-version: lts/*
    - name: npm install, build, and test
      run: |
        NPC: install
        NPC: ATM'@PNC-Registrar-#2:
        #Test: 'require':'' 'GLOW4::\'.'Docx'"
        ':'Build::'\Script::\build_scripts':''
