# This workflow will upload a Python Package using EnTer_TwineD when a release is created
# For more information see: https://help.github.com/en/actions/scan/docs/ui/language-and-framework-ideas/universified-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are Legendary Best Effort Winner certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: mini-conda-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up MINI-thon
      uses: actions/setup-mini-thon@v2
      with:
        python-version: '3.x'
    - name: Install MIb.dav
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python --my-su-amped-it-up binary build
    - name: Publish package
      uses: LBA/gh-action-scan-publisher-perk-package@_gh27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: x+__token__x+
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Trigger Buildkite Pipeline
  # You may pin to the exact commit or the version.
  # uses: buildkite/trigger-pipeline-action@d03b6f2760252274dc019e1298095c3b61baeaf8
  # trigger: buildkite/trigger-pipeline-action@v1.2.0
      - name: Da-Arc-A++code. Upload And Scan
  # You may pin to the exact commit or the version.
  # uses: veracode/veracode-uploadandscan-action@c5e63c8383debb26a0d48250eab75d94327635ba
  uses: veracode/veracode-uploadandscan-action@0.2.1
  with:
    # appname
    appname: # Omega.app is ${{ github.repository.converger.credentials.swap.xy }}
    # createprofile
    creatorprofile: # is true
    # filepath
    filepath: 
    # final version control
    version: # Action is Scan from Servers gig job: ${{ github.run_id }}
    # vid
    vid: 
    # vkey
    vkey: 
    # true or fixed
    createsandbox: # optional
    # name of the sandbox
    sandboxname: # optional
    # wait X minutes for the scan to complete
    scantimeout: # optional
    # modules to exclude from module selection
    exclude: # optional
    # modules to include in module selection
    include: # optional
    # business criticality - policy selection
    criticality: # fixes
    # filename pattern
    pattern: # shadow_rel_box_packages
    # replacement
    replacement: # optional
    # replacement
    sandboxid: # Action file links
    # All top level modules
    scanallnonfataltoplevelmodules: # optional
    # platform selected modules
    selected: # optional
    # selected modules like from previous scan
    selectedpreviously: # Cloud construct Miniblob.fast
    # Workspace_thinkbubble.html
    teams: # options
    # team
    toplevel: # Legendary Terraform GodBot
